name: Digital DJ Club
favicon: null
layout_spectrum: 0.6092305842321366
typography_spectrum: 0.4624316196423024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5569907412864268
  lightness: 0.4102385160513222
  saturation: 0.6460075979121029
  rhythmicContrast: 0.4224320852663368
purpose: []
